package com.app.enumeration;

public enum EmailType {
    REGISTRATION, NORMAL_INVESTMENT, QUICK_INVESTMENT, AUTO_INVESTMENT, DISBURSEMENT, REPAYMENT, CART_FIRST_TRIGGER,
    CART_LOAN_RAISED_TRIGGER, AUTOINVEST_PREF_CHANGED, PENDING_KYC, KYC_REJECTED, LOAN_CANCELLATION, 
    WITHDRAWAL_REJECTED, WITHDRAWAL_PROCESSED, WITHDRAWAL_REQUESTED, SUBSCRIPTION_PURCHASED, PAYMENT_FAILED, PASSWORD_RESET
}
